# Generated by Django 6.0.1 on 2026-04-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(max_length=250)),
                ('metodo_pago', models.CharField(default='Efectivo', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('EGRE', 'Egreso')], max_length=4)),
            ],
        ),
    ]
